---
- name: Install required DevOps tools
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name:
          - git
          - docker.io
          - openjdk-17-jdk
          - curl
          - wget
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes